// ChurnGuard i18n — ES / EN / FR / DE. Sin dependencias.
var I18N = {
es: {
  _meta: { title: "ChurnGuard — Churn y alto valor desde datos reales | F2P", description: "ChurnGuard ayuda a detectar señales de posible abandono y priorizar dónde actuar, desde 18.099 reseñas reales de Steam. Demo ilustrativa, piloto de 4 semanas con PlayNova Games." },
  nav: { problema: "Problema", datos: "Datos reales", solucion: "Solución", demo: "Demo", piloto: "Piloto", metodologia: "Metodología", cta: "Pedir piloto →" },
  hero: { badge: "● 18.099 reseñas reales · 6 F2P · cero sintéticos", h1a: "El abandono se ve venir", h1b: "en las señales tempranas", lede: "Estudiamos qué señales aparecen con más frecuencia entre quienes terminan abandonando y convertimos esas señales en <strong>prioridad, motivo y acción</strong> para Live-Ops. No adivinamos el futuro: ayudamos a decidir <strong>dónde actuar antes</strong>. Modelos auditables, validez probada <strong>juego por juego</strong>.", cta1: "Probar el simulador →", cta2: "Ver los datos reales", c1: "Jugadores reales etiquetados", c4: "ROC-AUC · Alto valor", logos: "6 títulos F2P", logos2: "pipeline reproducible" },
  mock: { bar: "live-ops · ranking semanal de riesgo", th1: "Jugador", th2: "Riesgo", th3: "Motivo", th4: "Acción", m1: "Pocas horas tempranas", a1: "Onboarding + evento diario", m2: "Señal antigua, título frío", a2: "Win-back + bundle retorno", m3: "No recomienda", a3: "Soporte proactivo", foot: "Demo ilustrativa · no es el modelo productivo · el piloto usa vuestros eventos reales" },
  prob: { title: "El problema, medido en datos reales", sub: "27,1% de los reseñistas pertenecen a la categoría de abandono que hemos definido. Y el engagement temprano muestra diferencias claras: Q1 (≤18 h) 35,7% frente a Q4 13,2% en nuestra muestra.", t1: "El abandono empieza pronto", p1: "Mediana de horas en reseña: 36,8 h en la categoría de abandono vs 120,6 h en activos. Las primeras horas pueden ser una ventana crítica para intentar enganchar al jugador.", t2: "Que guste no significa que se queden", p2: "En nuestra muestra, 26,5% de abandono entre quienes recomiendan vs 29,6% si no. La buena valoración por sí sola no debería ser la única señal para decidir a quién recuperar.", t3: "Cada juego tiene su propia historia", p3: "Dota 2 genera 3.000 reseñas en 3 días; Fall Guys en 470. El ritmo de la comunidad ayuda a entender en qué momento puede estar un juego — y dónde puede tener sentido concentrar esfuerzos." },
  data: { title: "Datos 100% reales, auditables", sub: "18.099 reseñas públicas de Steam (API pública, sin key, 2026-09-14) → 16.447 jugadores etiquetados. Cobertura del 100% en campos clave. Procedencia completa en <code>docs/08_datos_reales.md</code>.", th1: "Título", th2: "Etiquetados", th4: "Alto valor", th5: "p75 horas", note: "* Tasas dentro de nuestra muestra de personas que dejaron reseña y pertenecen a la categoría de abandono definida — no son la retención de esos juegos (documentado). Lo que generaliza son las relaciones, validadas juego por juego.", mini: "Lo que enseña cada figura (generadas por <code>notebooks/EDA.ipynb</code>)", f1t: "Estado por título", f1n: "Juegos vivos vs juegos en declive: dónde priorizar Live-Ops.", f2t: "Engagement temprano", f2n: "Q1 35,7% → Q4 13,2%: el hábito de las primeras horas decide.", f3t: "Satisfacción ≠ retención", f3n: "Recomendar apenas mueve la aguja (26,5% vs 29,6%).", zoom: "🔍 Clic para ampliar" },
  sol: { title: "Dos puntuaciones, dos decisiones", tag1: "Producto principal", d1: "Analiza las señales disponibles y da una <strong>puntuación de riesgo + motivo + acción</strong>. No es “tiene riesgo” a secas, es “tiene prioridad porque presenta poco engagement temprano, vamos a intentar recuperarlo con esta acción”. <strong>Sin mirar la recencia</strong>: solo señales del momento de la reseña.", n1: "Validez por título ROC 0.891–0.924 en los 6 juegos. Matriz test: [[2299,99],[218,674]]. Umbral 0.65 calibrado en validación interna (test intacto).", tag2: "Segunda línea · UA", d2: "Identifica perfiles que más se parecen a jugadores de mayor valor <strong>dentro de nuestros datos</strong> (top-25% horas + recomienda; threshold 0.55). Es un <strong>indicador aproximado</strong>: no tenemos gasto real y no decimos quién va a gastar. En un proyecto real se sustituye por los datos de compras del cliente.", n2: "Validez por título ROC 0.979–0.996. Indicador aproximado y transparente: los F2P no exponen pagos.", ht: "🔍 Honestidad técnica: qué podemos afirmar y qué no", h1: "<strong>Sin ventaja artificial:</strong> el modelo nunca ve horas totales, últimas 2 semanas, recencia, p75 ni (en conversión) el voto — definen las etiquetas. Verificable en <code>src/train_real.py</code>.", h2: "<strong>Sesgo declarado:</strong> muestra de personas que dejaron reseña, no de todos los jugadores; ventanas de observación desiguales; juegos PC F2P en Steam como los de PlayNova. Todo en <code>docs/08_datos_reales.md</code>.", h3: "<strong>Sin magia:</strong> una buena solución no es solo un número alto, es saber qué podemos afirmar y qué no. Artefactos versionados: <code>models/real_*.pkl</code>, <code>models/real_metrics.json</code>, DB de 2 MB." },
  demo: { title: "Demo: aquí no explicamos, lo enseñamos", sub: "Ajusta el perfil y mira prioridad, motivo y acción. Demo ilustrativa calibrada con las importancias reales — no es exactamente el modelo productivo.", hours: "Horas jugadas (en reseña):", hoursUnit: "h", games: "Juegos en la cuenta:", age: "Antigüedad de la señal:", ageUnit: "días", titleLab: "Título", t_dota: "Dota 2 (vivo)", t_apex: "Apex Legends (vivo)", t_poe: "Path of Exile (frío)", t_fall: "Fall Guys (en declive)", votedLab: "¿Recomienda el juego?", yes: "Sí", no: "No", p1: "⚠️ En riesgo", p2: "😐 Típico", p3: "✅ Sano", bTitle: "🧮 Calculadora de escenario (estimación, no garantía)", bDesc: "Escenario con nuestro indicador aproximado: ~19,9% encajaría en el grupo de alto valor. Es una <strong>estimación basada en nuestro proxy, no una garantía de ingresos</strong>. En un proyecto real lo sustituimos por los datos de PlayNova Games.", budget: "Budget ($/mes)", ltv: "LTV alto valor ($)", calc: "Calcular" },
  pilot: { title: "Piloto de 4 semanas: probarlo con vuestros datos", sub: "No os pedimos que creáis en ChurnGuard. Os pedimos cuatro semanas para demostrarlo con vuestros propios datos.", t1: "Semana 1 · Conectar", p1: "Export diario de eventos con identificadores anonimizados (CSV o endpoint): sesiones, progresión, compras, atribución. Firma DPA. Nada invasivo el día 1.", t2: "Semanas 2–3 · Probar", p2: "Grupo de mayor prioridad + acción recomendada vs grupo con tratamiento habitual. Métrica primaria: retención. Secundarias: 2ª sesión y conversión.", t3: "Semana 4 · Decidir", p3: "Medimos si ha mejorado la retención y la conversión. Si funciona, tenemos argumentos para continuar. Si no funciona, también lo sabremos. Precio piloto: <strong>2.500 €</strong> fijos.", ht: "🔌 Integración y GDPR", h1: "<strong>Input:</strong> CSV diario o POST JSON a <code>/score</code> → <code>{p_churn, motivo, acción}</code>. Latencia &lt; 200 ms p95.", h2: "<strong>Privacidad:</strong> IDs anonimizados, sin PII. Borrado a petición, retención 90 días.", h3: "<strong>Stack:</strong> scikit-learn versionado (seed 42), <code>.pkl</code> con encoders. Re-entreno semanal." },
  met: { title: "Cómo trabajamos", d10t: "Paso 1 · Idea", d10p: "Foco: señales de posible abandono + perfiles de mayor valor para F2P. Cliente piloto: PlayNova Games.", d11t: "Paso 2 · Cliente y datos", d11p: "APIs evaluadas (Steam ✓, OpenDota ✗ por timeouts). Schema real en la DB.", d12t: "Paso 3 · Dataset real", d12p: ": 18.099 reseñas → 16.447 etiquetados.", d13t: "Paso 4 · Análisis", d13p: ": engagement temprano, fase por título, voto≠retención.", d14t: "Paso 5 · Solución", d14p: " anti-fuga + ", d14p2: ": ROC 0.89–0.92 por juego.", faqT: "Preguntas que haría tu CTO", q1: "¿De dónde salen los datos?", a1: "De la API pública de reseñas de Steam (sin key): 18.099 reseñas de 6 F2P del 2026-09-14. Crudo re-descargable, DB y resumen versionados, procedencia en <code>docs/08_datos_reales.md</code>.", q2: "¿El 91% de Fall Guys significa que el 91% de sus jugadores han abandonado?", a2: "No: es el porcentaje dentro de nuestra muestra de personas que dejaron reseña que pertenecen a la categoría de abandono definida. Una persona que escribe una reseña no representa a todos los jugadores. Lo que generaliza son las relaciones, validadas título a título.", q3: "¿Hay fuga? La antigüedad pesa 0.50…", a3: "Es señal real (ritmo de reseñas = momento del título) pero con ventana desigual: documentado como limitación. El modelo nunca ve recencia ni horas totales; el piloto trabajará con ventanas fijas y vuestros eventos reales.", q4: "¿Tenemos datos reales de cuánto gasta cada jugador?", a4: "No. Utilizamos un indicador aproximado (top-25% horas + recomienda), así presentado en todas partes. En un proyecto real se sustituye por los datos de compras de PlayNova Games.", q5: "¿La demo que hemos visto es exactamente el modelo productivo?", a5: "No: es una demo ilustrativa calibrada para convertir señales en decisiones. El modelo real está en <code>models/real_*.pkl</code>; en el piloto exponemos <code>/score</code> con vuestros datos.", q6: "¿Por qué el F1 varía por título si el ROC es bueno en los 6?", a6: "Porque la prevalencia va del 5% (Dota 2, Apex) al 91% (Fall Guys) y usamos un umbral global (0.65) calibrado en validación del conjunto. El ROC mide el ranking dentro de cada juego (0.891–0.924 en los 6); el F1 depende del punto de corte. En el piloto calibramos el umbral por título." },
  foot: { title: "PlayNova, ¿queréis que descubramos juntos cuántos jugadores podemos recuperar?", sub: "ChurnGuard no pretende adivinar el futuro. Pretende ayudaros a detectar señales antes y decidir dónde actuar. 4 semanas · 2.500 € · datos reales · experimento controlado.", cta: "pedir piloto · 2.500 € →", base: "ChurnGuard — NO PAIN NO GAME · 2026<br>Datos públicos de Steam (18.099 reseñas, 2026-09-14) · Cliente piloto: PlayNova Games", top: "volver arriba ↑" },
  sim: { levelHigh: "🔴 Riesgo alto", levelMid: "🟡 Riesgo medio", levelLow: "🟢 Riesgo bajo", motiveEarly: "Engagement temprano bajo (Q1: 35,7% de churn)", actionEarly: "Onboarding + evento diario personalizado en 24 h.", motiveOld: "Señal antigua en título frío", actionOld: "Campaña win-back + bundle de retorno.", motiveNoRec: "No recomienda (29,6% de churn)", actionNoRec: "Soporte proactivo + oferta de guardado.", motiveDecline: "Título en fase de declive", actionDecline: "Contenido/evento de retorno + recordatorio.", motiveHealthy: "Perfil sano", actionHealthy: "Mantener cadencia; pase de temporada como acelerador.", motiveLabel: "Motivo probable:", actionLabel: "Acción playbook:", budgetA: "en grupo de alto valor aprox. (19,9% en nuestra muestra)", budgetB: "de valor potencial con LTV $", budgetC: "Estimación basada en nuestro proxy, no una garantía de ingresos. En proyecto real se sustituye por datos reales de PlayNova Games.", lbSuffix: "(pulsa Esc o clic fuera para cerrar)" }
},
en: {
  _meta: { title: "ChurnGuard — Churn and high value from real data | F2P", description: "ChurnGuard helps detect early churn signals and prioritise where to act, from 18,099 real Steam reviews. Illustrative demo, 4-week pilot with PlayNova Games." },
  nav: { problema: "Problem", datos: "Real data", solucion: "Solution", demo: "Demo", piloto: "Pilot", metodologia: "Methodology", cta: "Request pilot →" },
  hero: { badge: "● 18,099 real reviews · 6 F2P · zero synthetic", h1a: "Abandonment can be seen coming", h1b: "in the early signals", lede: "We study which signals appear most often among players who end up leaving and turn them into <strong>priority, reason and action</strong> for Live-Ops. We don't guess the future: we help decide <strong>where to act first</strong>. Auditable models, proven <strong>game by game</strong>.", cta1: "Try the simulator →", cta2: "See the real data", c1: "Labelled real players", c4: "ROC-AUC · High value", logos: "6 F2P titles", logos2: "reproducible pipeline" },
  mock: { bar: "live-ops · weekly risk ranking", th1: "Player", th2: "Risk", th3: "Reason", th4: "Action", m1: "Few early hours", a1: "Onboarding + daily event", m2: "Old signal, cold title", a2: "Win-back + return bundle", m3: "Doesn't recommend", a3: "Proactive support", foot: "Illustrative demo · not the production model · the pilot uses your real events" },
  prob: { title: "The problem, measured in real data", sub: "27.1% of reviewers fall into the churn category we defined. And early engagement shows clear gaps: Q1 (≤18 h) 35.7% vs Q4 13.2% in our sample.", t1: "Churn starts early", p1: "Median review-time hours: 36.8 h in the churn category vs 120.6 h when active. The first hours can be a critical window to hook the player.", t2: "Liking it doesn't mean staying", p2: "In our sample, 26.5% churn among recommenders vs 29.6% otherwise. A good rating alone shouldn't be the only signal for who to win back.", t3: "Every game has its own story", p3: "Dota 2 gets 3,000 reviews in 3 days; Fall Guys in 470. Community pace helps tell which phase a game may be in — and where it makes sense to focus effort." },
  data: { title: "100% real, auditable data", sub: "18,099 public Steam reviews (public API, no key, 2026-09-14) → 16,447 labelled players. 100% coverage on key fields. Full provenance in <code>docs/08_datos_reales.md</code>.", th1: "Title", th2: "Labelled", th4: "High value", th5: "p75 hours", note: "* Rates within our sample of reviewers in the defined churn category — not those games' retention (documented). What generalises are the relationships, validated game by game.", mini: "What each chart shows (generated by <code>notebooks/EDA.ipynb</code>)", f1t: "Status by title", f1n: "Live vs declining games: where to focus Live-Ops.", f2t: "Early engagement", f2n: "Q1 35.7% → Q4 13.2%: early-hours habit decides.", f3t: "Satisfaction ≠ retention", f3n: "Recommending barely moves the needle (26.5% vs 29.6%).", zoom: "🔍 Click to enlarge" },
  sol: { title: "Two scores, two decisions", tag1: "Flagship product", d1: "It analyses the available signals and returns a <strong>risk score + reason + action</strong>. Not just “at risk”, but “priority because of low early engagement — let's try to win them back with this action”. <strong>Without looking at recency</strong>: only review-time signals.", n1: "Per-title validity ROC 0.891–0.924 across 6 games. Test matrix: [[2299,99],[218,674]]. Threshold 0.65 tuned on internal validation (test untouched).", tag2: "Second line · UA", d2: "It finds profiles most similar to higher-value players <strong>within our data</strong> (top-25% hours + recommends; threshold 0.55). It is an <strong>approximate indicator</strong>: we have no real spend and don't claim who will spend. In a real project it is replaced by the client's purchase data.", n2: "Per-title validity ROC 0.979–0.996. Approximate, transparent indicator: F2P games don't expose payments.", ht: "🔍 Technical honesty: what we can and can't claim", h1: "<strong>No unfair advantage:</strong> the model never sees total hours, last 2 weeks, recency, p75 or (for conversion) the vote — they define the labels. Verifiable in <code>src/train_real.py</code>.", h2: "<strong>Declared bias:</strong> sample of reviewers, not all players; uneven observation windows; PC F2P games on Steam like PlayNova's. All in <code>docs/08_datos_reales.md</code>.", h3: "<strong>No magic:</strong> a good solution isn't just a high number, it's knowing what we can and can't claim. Versioned artefacts: <code>models/real_*.pkl</code>, <code>models/real_metrics.json</code>, 2 MB DB." },
  demo: { title: "Demo: we don't explain, we show", sub: "Tune the profile and see priority, reason and action. Illustrative demo calibrated on real importances — not exactly the production model.", hours: "Hours played (at review):", hoursUnit: "h", games: "Games on the account:", age: "Signal age:", ageUnit: "days", titleLab: "Title", t_dota: "Dota 2 (live)", t_apex: "Apex Legends (live)", t_poe: "Path of Exile (cold)", t_fall: "Fall Guys (declining)", votedLab: "Does the player recommend the game?", yes: "Yes", no: "No", p1: "⚠️ At risk", p2: "😐 Typical", p3: "✅ Healthy", bTitle: "🧮 Scenario calculator (estimate, not a guarantee)", bDesc: "Scenario with our approximate indicator: ~19.9% would fit the high-value group. This is an <strong>estimate based on our proxy, not a revenue guarantee</strong>. In a real project we replace it with PlayNova Games data.", budget: "Budget ($/month)", ltv: "High-value LTV ($)", calc: "Calculate" },
  pilot: { title: "4-week pilot: prove it on your data", sub: "We're not asking you to believe in ChurnGuard. We're asking for four weeks to prove it on your own data.", t1: "Week 1 · Connect", p1: "Daily event export with anonymised IDs (CSV or endpoint): sessions, progression, purchases, attribution. DPA signed. Nothing invasive on day 1.", t2: "Weeks 2–3 · Test", p2: "Top-priority group + recommended action vs business-as-usual group. Primary metric: retention. Secondary: 2nd session and conversion.", t3: "Week 4 · Decide", p3: "We measure whether retention and conversion improved. If it works, we have grounds to continue. If not, we'll know too. Pilot price: <strong>€2,500</strong> fixed.", ht: "🔌 Integration & GDPR", h1: "<strong>Input:</strong> daily CSV or POST JSON to <code>/score</code> → <code>{p_churn, reason, action}</code>. Latency &lt; 200 ms p95.", h2: "<strong>Privacy:</strong> anonymised IDs, no PII. Deletion on request, 90-day retention.", h3: "<strong>Stack:</strong> versioned scikit-learn (seed 42), <code>.pkl</code> with encoders. Weekly retraining." },
  met: { title: "How we work", d10t: "Step 1 · Idea", d10p: "Focus: possible-churn signals + higher-value profiles for F2P. Pilot client: PlayNova Games.", d11t: "Step 2 · Client & data", d11p: "APIs evaluated (Steam ✓, OpenDota ✗ timeouts). Real schema in the DB.", d12t: "Step 3 · Real dataset", d12p: ": 18,099 reviews → 16,447 labelled.", d13t: "Step 4 · Analysis", d13p: ": early engagement, phase per title, vote≠retention.", d14t: "Step 5 · Solution", d14p: " leak-free + ", d14p2: ": ROC 0.89–0.92 per game.", faqT: "Questions your CTO would ask", q1: "Where does the data come from?", a1: "From Steam's public review API (no key): 18,099 reviews of 6 F2P games from 2026-09-14. Re-downloadable raw data, versioned DB and summary, provenance in <code>docs/08_datos_reales.md</code>.", q2: "Does Fall Guys' 91% mean 91% of its players left?", a2: "No: it's the share within our sample of reviewers in the defined churn category. A reviewer doesn't represent all players. What generalises are the relationships, validated title by title.", q3: "Any leakage? Signal age weighs 0.50…", a3: "It's a real signal (review pace = title momentum) but with uneven windows: documented as a limitation. The model never sees recency or total hours; the pilot will use fixed windows and your real events.", q4: "Do we have real spend per player?", a4: "No. We use an approximate indicator (top-25% hours + recommends), presented as such everywhere. In a real project it's replaced by PlayNova Games purchase data.", q5: "Is the demo exactly the production model?", a5: "No: it's an illustrative demo calibrated to turn signals into decisions. The real model lives in <code>models/real_*.pkl</code>; in the pilot we expose <code>/score</code> on your data.", q6: "Why does F1 vary by title if ROC is good on all 6?", a6: "Because prevalence ranges from 5% (Dota 2, Apex) to 91% (Fall Guys) and we use one global threshold (0.65) tuned on aggregate validation. ROC measures within-game ranking (0.891–0.924 on all 6); F1 depends on the cut point. In the pilot we calibrate the threshold per title." },
  foot: { title: "PlayNova, shall we find out together how many players we can win back?", sub: "ChurnGuard doesn't claim to predict the future. It helps you spot signals earlier and decide where to act. 4 weeks · €2,500 · real data · controlled experiment.", cta: "request pilot · €2,500 →", base: "ChurnGuard — NO PAIN NO GAME · 2026<br>Public Steam data (18,099 reviews, 2026-09-14) · Pilot client: PlayNova Games", top: "back to top ↑" },
  sim: { levelHigh: "🔴 High risk", levelMid: "🟡 Medium risk", levelLow: "🟢 Low risk", motiveEarly: "Low early engagement (Q1: 35.7% churn)", actionEarly: "Personalised onboarding + daily event within 24 h.", motiveOld: "Old signal on a cold title", actionOld: "Win-back campaign + return bundle.", motiveNoRec: "Doesn't recommend (29.6% churn)", actionNoRec: "Proactive support + save offer.", motiveDecline: "Declining-phase title", actionDecline: "Return content/event + reminder.", motiveHealthy: "Healthy profile", actionHealthy: "Keep cadence; season pass as accelerator.", motiveLabel: "Likely reason:", actionLabel: "Playbook action:", budgetA: "in the approximate high-value group (19.9% in our sample)", budgetB: "of potential value at LTV $", budgetC: "Estimate based on our proxy, not a revenue guarantee. In a real project it is replaced by PlayNova Games data.", lbSuffix: "(press Esc or click outside to close)" }
},
fr: {
  _meta: { title: "ChurnGuard — Churn et haute valeur à partir de données réelles | F2P", description: "ChurnGuard aide à détecter les signaux précoces d'abandon et à prioriser où agir, à partir de 18 099 avis Steam réels. Démo illustrative, pilote de 4 semaines avec PlayNova Games." },
  nav: { problema: "Problème", datos: "Données réelles", solucion: "Solution", demo: "Démo", piloto: "Pilote", metodologia: "Méthodologie", cta: "Demander un pilote →" },
  hero: { badge: "● 18 099 avis réels · 6 F2P · zéro synthétique", h1a: "L'abandon se voit venir", h1b: "dans les signaux précoces", lede: "Nous étudions les signaux les plus fréquents chez les joueurs qui finissent par partir et les convertissons en <strong>priorité, motif et action</strong> pour le Live-Ops. Nous ne prédisons pas l'avenir : nous aidons à décider <strong>où agir d'abord</strong>. Modèles auditables, validité prouvée <strong>jeu par jeu</strong>.", cta1: "Tester le simulateur →", cta2: "Voir les données réelles", c1: "Joueurs réels étiquetés", c4: "ROC-AUC · Haute valeur", logos: "6 titres F2P", logos2: "pipeline reproductible" },
  mock: { bar: "live-ops · classement hebdo du risque", th1: "Joueur", th2: "Risque", th3: "Motif", th4: "Action", m1: "Peu d'heures précoces", a1: "Onboarding + événement quotidien", m2: "Signal ancien, titre froid", a2: "Win-back + bundle retour", m3: "Ne recommande pas", a3: "Support proactif", foot: "Démo illustrative · pas le modèle productif · le pilote utilise vos vrais événements" },
  prob: { title: "Le problème, mesuré en données réelles", sub: "27,1 % des auteurs d'avis entrent dans la catégorie d'abandon définie. Et l'engagement précoce montre des écarts nets : Q1 (≤18 h) 35,7 % contre Q4 13,2 % dans notre échantillon.", t1: "L'abandon commence tôt", p1: "Médiane d'heures à l'avis : 36,8 h dans la catégorie abandon contre 120,6 h chez les actifs. Les premières heures peuvent être une fenêtre critique pour accrocher le joueur.", t2: "Aimer ne veut pas dire rester", p2: "Dans notre échantillon, 26,5 % d'abandon chez ceux qui recommandent contre 29,6 % sinon. Une bonne note seule ne devrait pas être le seul signal pour choisir qui récupérer.", t3: "Chaque jeu a sa propre histoire", p3: "Dota 2 génère 3 000 avis en 3 jours ; Fall Guys en 470. Le rythme de la communauté aide à comprendre la phase d'un jeu — et où concentrer les efforts." },
  data: { title: "Données 100 % réelles, auditables", sub: "18 099 avis Steam publics (API publique, sans clé, 2026-09-14) → 16 447 joueurs étiquetés. Couverture 100 % sur les champs clés. Provenance complète dans <code>docs/08_datos_reales.md</code>.", th1: "Titre", th2: "Étiquetés", th4: "Haute valeur", th5: "p75 heures", note: "* Taux dans notre échantillon d'auteurs d'avis dans la catégorie d'abandon définie — pas la rétention de ces jeux (documenté). Ce qui se généralise, ce sont les relations, validées jeu par jeu.", mini: "Ce que montre chaque figure (générées par <code>notebooks/EDA.ipynb</code>)", f1t: "Statut par titre", f1n: "Jeux vivants vs en déclin : où prioriser le Live-Ops.", f2t: "Engagement précoce", f2n: "Q1 35,7 % → Q4 13,2 % : l'habitude des premières heures décide.", f3t: "Satisfaction ≠ rétention", f3n: "Recommander change à peine la donne (26,5 % vs 29,6 %).", zoom: "🔍 Cliquer pour agrandir" },
  sol: { title: "Deux scores, deux décisions", tag1: "Produit principal", d1: "Analyse les signaux disponibles et renvoie <strong>score de risque + motif + action</strong>. Pas seulement « à risque », mais « prioritaire car faible engagement précoce — essayons de le récupérer avec cette action ». <strong>Sans regarder la récence</strong> : seuls les signaux au moment de l'avis.", n1: "Validité par titre ROC 0,891–0,924 sur 6 jeux. Matrice test : [[2299,99],[218,674]]. Seuil 0,65 calibré en validation interne (test intact).", tag2: "Seconde ligne · UA", d2: "Identifie les profils les plus proches des joueurs à haute valeur <strong>dans nos données</strong> (top-25 % heures + recommande ; seuil 0,55). C'est un <strong>indicateur approximatif</strong> : sans dépense réelle, sans dire qui va dépenser. En projet réel, remplacé par les achats du client.", n2: "Validité par titre ROC 0,979–0,996. Indicateur approximatif et transparent : les F2P n'exposent pas les paiements.", ht: "🔍 Honnêteté technique : ce que l'on peut affirmer ou non", h1: "<strong>Sans avantage artificiel :</strong> le modèle ne voit jamais les heures totales, les 2 dernières semaines, la récence, le p75 ni (en conversion) le vote — ils définissent les étiquettes. Vérifiable dans <code>src/train_real.py</code>.", h2: "<strong>Biais déclaré :</strong> échantillon d'auteurs d'avis, pas tous les joueurs ; fenêtres d'observation inégales ; jeux PC F2P sur Steam comme ceux de PlayNova. Tout dans <code>docs/08_datos_reales.md</code>.", h3: "<strong>Sans magie :</strong> une bonne solution n'est pas qu'un chiffre élevé, c'est savoir ce que l'on peut affirmer ou non. Artefacts versionnés : <code>models/real_*.pkl</code>, <code>models/real_metrics.json</code>, DB de 2 Mo." },
  demo: { title: "Démo : on ne raconte pas, on montre", sub: "Ajustez le profil et voyez priorité, motif et action. Démo illustrative calibrée sur les importances réelles — pas exactement le modèle productif.", hours: "Heures jouées (à l'avis) :", hoursUnit: "h", games: "Jeux sur le compte :", age: "Ancienneté du signal :", ageUnit: "jours", titleLab: "Titre", t_dota: "Dota 2 (vivant)", t_apex: "Apex Legends (vivant)", t_poe: "Path of Exile (froid)", t_fall: "Fall Guys (en déclin)", votedLab: "Recommande-t-il le jeu ?", yes: "Oui", no: "Non", p1: "⚠️ À risque", p2: "😐 Typique", p3: "✅ Sain", bTitle: "🧮 Calculateur de scénario (estimation, pas garantie)", bDesc: "Scénario avec notre indicateur approximatif : ~19,9 % entreraient dans le groupe haute valeur. C'est une <strong>estimation basée sur notre proxy, pas une garantie de revenus</strong>. En projet réel, remplacé par les données PlayNova Games.", budget: "Budget ($/mois)", ltv: "LTV haute valeur ($)", calc: "Calculer" },
  pilot: { title: "Pilote de 4 semaines : prouver sur vos données", sub: "Nous ne vous demandons pas de croire en ChurnGuard. Donnez-nous quatre semaines pour le prouver sur vos propres données.", t1: "Semaine 1 · Connecter", p1: "Export quotidien d'événements anonymisés (CSV ou endpoint) : sessions, progression, achats, attribution. DPA signé. Rien d'invasif au jour 1.", t2: "Semaines 2–3 · Tester", p2: "Groupe prioritaire + action recommandée vs groupe témoin habituel. Métrique primaire : rétention. Secondaires : 2e session et conversion.", t3: "Semaine 4 · Décider", p3: "On mesure si la rétention et la conversion se sont améliorées. Si ça marche, on continue. Sinon, on le saura aussi. Prix pilote : <strong>2 500 €</strong> fixes.", ht: "🔌 Intégration et RGPD", h1: "<strong>Entrée :</strong> CSV quotidien ou POST JSON vers <code>/score</code> → <code>{p_churn, motif, action}</code>. Latence &lt; 200 ms p95.", h2: "<strong>Confidentialité :</strong> IDs anonymisés, sans PII. Suppression sur demande, rétention 90 jours.", h3: "<strong>Stack :</strong> scikit-learn versionné (seed 42), <code>.pkl</code> avec encodeurs. Ré-entraînement hebdo." },
  met: { title: "Notre méthode", d10t: "Étape 1 · Idée", d10p: "Focus : signaux d'abandon possible + profils haute valeur pour F2P. Client pilote : PlayNova Games.", d11t: "Étape 2 · Client et données", d11p: "APIs évaluées (Steam ✓, OpenDota ✗ timeouts). Schéma réel dans la DB.", d12t: "Étape 3 · Dataset réel", d12p: " : 18 099 avis → 16 447 étiquetés.", d13t: "Étape 4 · Analyse", d13p: " : engagement précoce, phase par titre, vote≠rétention.", d14t: "Étape 5 · Solution", d14p: " anti-fuite + ", d14p2: " : ROC 0,89–0,92 par jeu.", faqT: "Questions que poserait votre CTO", q1: "D'où viennent les données ?", a1: "De l'API publique d'avis Steam (sans clé) : 18 099 avis de 6 jeux F2P du 2026-09-14. Brut re-téléchargeable, DB et résumé versionnés, provenance dans <code>docs/08_datos_reales.md</code>.", q2: "Les 91 % de Fall Guys veulent-ils dire que 91 % de ses joueurs sont partis ?", a2: "Non : c'est la part dans notre échantillon d'auteurs d'avis dans la catégorie d'abandon définie. Un auteur d'avis ne représente pas tous les joueurs. Ce qui se généralise, ce sont les relations, validées titre par titre.", q3: "Fuite ? L'ancienneté pèse 0,50…", a3: "C'est un vrai signal (rythme des avis = moment du titre) mais à fenêtre inégale : documenté comme limite. Le modèle ne voit jamais la récence ni les heures totales ; le pilote utilisera des fenêtres fixes et vos vrais événements.", q4: "Avons-nous la dépense réelle par joueur ?", a4: "Non. Nous utilisons un indicateur approximatif (top-25 % heures + recommande), présenté comme tel partout. En projet réel, remplacé par les achats PlayNova Games.", q5: "La démo est-elle exactement le modèle productif ?", a5: "Non : c'est une démo illustrative calibrée pour transformer les signaux en décisions. Le vrai modèle est dans <code>models/real_*.pkl</code> ; en pilote on expose <code>/score</code> sur vos données.", q6: "Pourquoi le F1 varie-t-il par titre si le ROC est bon sur les 6 ?", a6: "Parce que la prévalence va de 5 % (Dota 2, Apex) à 91 % (Fall Guys) avec un seuil global (0,65) calibré en validation agrégée. Le ROC mesure le classement dans chaque jeu (0,891–0,924 sur les 6) ; le F1 dépend du seuil. En pilote, on calibre le seuil par titre." },
  foot: { title: "PlayNova, découvrons ensemble combien de joueurs nous pouvons récupérer ?", sub: "ChurnGuard ne prétend pas prédire l'avenir. Il aide à détecter les signaux plus tôt et à décider où agir. 4 semaines · 2 500 € · données réelles · expérience contrôlée.", cta: "demander un pilote · 2 500 € →", base: "ChurnGuard — NO PAIN NO GAME · 2026<br>Données Steam publiques (18 099 avis, 2026-09-14) · Client pilote : PlayNova Games", top: "retour en haut ↑" },
  sim: { levelHigh: "🔴 Risque élevé", levelMid: "🟡 Risque moyen", levelLow: "🟢 Risque faible", motiveEarly: "Faible engagement précoce (Q1 : 35,7 % de churn)", actionEarly: "Onboarding personnalisé + événement quotidien sous 24 h.", motiveOld: "Signal ancien sur titre froid", actionOld: "Campagne win-back + bundle retour.", motiveNoRec: "Ne recommande pas (29,6 % de churn)", actionNoRec: "Support proactif + offre de sauvegarde.", motiveDecline: "Titre en phase de déclin", actionDecline: "Contenu/événement retour + rappel.", motiveHealthy: "Profil sain", actionHealthy: "Garder le rythme ; passe de saison comme accélérateur.", motiveLabel: "Motif probable :", actionLabel: "Action playbook :", budgetA: "dans le groupe haute valeur approx. (19,9 % de notre échantillon)", budgetB: "de valeur potentielle avec LTV $", budgetC: "Estimation basée sur notre proxy, pas une garantie de revenus. En projet réel, remplacée par les données PlayNova Games.", lbSuffix: "(Échap ou clic dehors pour fermer)" }
},
de: {
  _meta: { title: "ChurnGuard — Churn und High-Value aus echten Daten | F2P", description: "ChurnGuard hilft, frühe Abwanderungssignale zu erkennen und zu priorisieren, wo zu handeln ist – aus 18.099 echten Steam-Reviews. Illustrative Demo, 4-Wochen-Pilot mit PlayNova Games." },
  nav: { problema: "Problem", datos: "Echte Daten", solucion: "Lösung", demo: "Demo", piloto: "Pilot", metodologia: "Methodik", cta: "Pilot anfragen →" },
  hero: { badge: "● 18.099 echte Reviews · 6 F2P · null synthetisch", h1a: "Abwanderung kündigt sich an", h1b: "in den frühen Signalen", lede: "Wir untersuchen, welche Signale bei Spielern, die am Ende gehen, am häufigsten auftreten, und machen daraus <strong>Priorität, Grund und Aktion</strong> für Live-Ops. Wir raten die Zukunft nicht: Wir helfen zu entscheiden, <strong>wo zuerst zu handeln ist</strong>. Auditierbare Modelle, <strong>Spiel für Spiel</strong> belegt.", cta1: "Simulator testen →", cta2: "Echte Daten ansehen", c1: "Gelabelte echte Spieler", c4: "ROC-AUC · High-Value", logos: "6 F2P-Titel", logos2: "reproduzierbare Pipeline" },
  mock: { bar: "Live-Ops · wöchentliches Risiko-Ranking", th1: "Spieler", th2: "Risiko", th3: "Grund", th4: "Aktion", m1: "Wenige frühe Stunden", a1: "Onboarding + Daily-Event", m2: "Altes Signal, kalter Titel", a2: "Win-back + Return-Bundle", m3: "Empfiehlt nicht", a3: "Proaktiver Support", foot: "Illustrative Demo · nicht das Produktivmodell · der Pilot nutzt eure echten Events" },
  prob: { title: "Das Problem, gemessen in echten Daten", sub: "27,1 % der Reviewer fallen in unsere definierte Abwanderungskategorie. Und frühes Engagement zeigt klare Unterschiede: Q1 (≤18 h) 35,7 % vs. Q4 13,2 % in unserer Stichprobe.", t1: "Abwanderung beginnt früh", p1: "Mediane Review-Stunden: 36,8 h in der Abwanderungskategorie vs. 120,6 h bei Aktiven. Die ersten Stunden können ein kritisches Fenster sein, um Spieler zu binden.", t2: "Mögen heißt nicht bleiben", p2: "In unserer Stichprobe: 26,5 % Churn bei Empfehlern vs. 29,6 % sonst. Eine gute Bewertung allein sollte nicht das einzige Signal sein, wen wir zurückgewinnen.", t3: "Jedes Spiel hat seine eigene Geschichte", p3: "Dota 2 erzeugt 3.000 Reviews in 3 Tagen; Fall Guys in 470. Das Community-Tempo zeigt, in welcher Phase ein Spiel sein kann — und wo Fokus lohnt." },
  data: { title: "100 % echte, auditierbare Daten", sub: "18.099 öffentliche Steam-Reviews (öffentliche API, ohne Key, 2026-09-14) → 16.447 gelabelte Spieler. 100 % Abdeckung der Kernfelder. Vollständige Herkunft in <code>docs/08_datos_reales.md</code>.", th1: "Titel", th2: "Gelabelt", th4: "High-Value", th5: "p75 Stunden", note: "* Raten innerhalb unserer Reviewer-Stichprobe in der definierten Kategorie — nicht die Retention dieser Spiele (dokumentiert). Was generalisiert, sind die Zusammenhänge, Spiel für Spiel validiert.", mini: "Was jede Grafik zeigt (erzeugt von <code>notebooks/EDA.ipynb</code>)", f1t: "Status pro Titel", f1n: "Lebendige vs. schrumpfende Spiele: wo Live-Ops priorisieren.", f2t: "Frühes Engagement", f2n: "Q1 35,7 % → Q4 13,2 %: Gewohnheit der ersten Stunden entscheidet.", f3t: "Zufriedenheit ≠ Bindung", f3n: "Empfehlen bewegt kaum etwas (26,5 % vs. 29,6 %).", zoom: "🔍 Klicken zum Vergrößern" },
  sol: { title: "Zwei Scores, zwei Entscheidungen", tag1: "Hauptprodukt", d1: "Analysiert die verfügbaren Signale und liefert <strong>Risiko-Score + Grund + Aktion</strong>. Nicht nur „riskant“, sondern „Priorität wegen geringem frühem Engagement — wir versuchen es mit dieser Aktion zurückzugewinnen“. <strong>Ohne Blick auf Recency</strong>: nur Signale zum Review-Zeitpunkt.", n1: "Validität pro Titel ROC 0,891–0,924 in 6 Spielen. Test-Matrix: [[2299,99],[218,674]]. Threshold 0,65 in interner Validierung kalibriert (Test unberührt).", tag2: "Zweite Linie · UA", d2: "Findet Profile, die Spielern mit höherem Wert <strong>in unseren Daten</strong> am ähnlichsten sind (Top-25 % Stunden + empfiehlt; Threshold 0,55). Es ist ein <strong>Näherungsindikator</strong>: ohne echte Ausgaben, ohne zu sagen, wer ausgeben wird. Im Echtprojekt ersetzt durch Kaufdaten des Kunden.", n2: "Validität pro Titel ROC 0,979–0,996. Näherungsweise, transparent: F2P-Spiele legen Zahlungen nicht offen.", ht: "🔍 Technische Ehrlichkeit: was wir sagen können — und was nicht", h1: "<strong>Kein unfairer Vorteil:</strong> Das Modell sieht nie Gesamtstunden, letzte 2 Wochen, Recency, p75 oder (bei Conversion) das Votum — sie definieren die Labels. Prüfbar in <code>src/train_real.py</code>.", h2: "<strong>Deklarierter Bias:</strong> Stichprobe von Reviewern, nicht aller Spieler; ungleiche Beobachtungsfenster; PC-F2P-Spiele auf Steam wie die von PlayNova. Alles in <code>docs/08_datos_reales.md</code>.", h3: "<strong>Keine Magie:</strong> Eine gute Lösung ist nicht nur eine hohe Zahl, sondern zu wissen, was man sagen kann und was nicht. Versionierte Artefakte: <code>models/real_*.pkl</code>, <code>models/real_metrics.json</code>, 2-MB-DB." },
  demo: { title: "Demo: Wir erklären nicht, wir zeigen", sub: "Profil anpassen und Priorität, Grund und Aktion sehen. Illustrative, an realen Importances kalibrierte Demo — nicht exakt das Produktivmodell.", hours: "Gespielte Stunden (zum Review):", hoursUnit: "Std.", games: "Spiele auf dem Konto:", age: "Signalalter:", ageUnit: "Tage", titleLab: "Titel", t_dota: "Dota 2 (lebendig)", t_apex: "Apex Legends (lebendig)", t_poe: "Path of Exile (kalt)", t_fall: "Fall Guys (schrumpfend)", votedLab: "Empfiehlt das Spiel?", yes: "Ja", no: "Nein", p1: "⚠️ Gefährdet", p2: "😐 Typisch", p3: "✅ Gesund", bTitle: "🧮 Szenario-Rechner (Schätzung, keine Garantie)", bDesc: "Szenario mit unserem Näherungsindikator: ~19,9 % fielen in die High-Value-Gruppe. Das ist eine <strong>Schätzung auf Proxy-Basis, keine Umsatzgarantie</strong>. Im Echtprojekt ersetzen wir sie durch PlayNova-Games-Daten.", budget: "Budget ($/Monat)", ltv: "High-Value-LTV ($)", calc: "Berechnen" },
  pilot: { title: "4-Wochen-Pilot: Beweis mit euren Daten", sub: "Wir bitten nicht um Glauben an ChurnGuard. Wir bitten um vier Wochen, um es mit euren eigenen Daten zu beweisen.", t1: "Woche 1 · Anbinden", p1: "Täglicher Event-Export mit anonymisierten IDs (CSV oder Endpoint): Sessions, Progression, Käufe, Attribution. DPA unterschrieben. Nichts Invasives an Tag 1.", t2: "Wochen 2–3 · Testen", p2: "Top-Prioritätsgruppe + empfohlene Aktion vs. Kontrollgruppe wie bisher. Primärmetrik: Retention. Sekundär: 2. Session und Conversion.", t3: "Woche 4 · Entscheiden", p3: "Wir messen, ob Retention und Conversion besser wurden. Wenn ja, machen wir weiter. Wenn nicht, wissen wir es auch. Pilotpreis: <strong>2.500 €</strong> fix.", ht: "🔌 Integration & DSGVO", h1: "<strong>Input:</strong> tägliches CSV oder POST-JSON an <code>/score</code> → <code>{p_churn, Grund, Aktion}</code>. Latenz &lt; 200 ms p95.", h2: "<strong>Privatsphäre:</strong> anonymisierte IDs, keine PII. Löschung auf Wunsch, 90 Tage Aufbewahrung.", h3: "<strong>Stack:</strong> versioniertes scikit-learn (Seed 42), <code>.pkl</code> mit Encodern. Wöchentliches Retraining." },
  met: { title: "So arbeiten wir", d10t: "Schritt 1 · Idee", d10p: "Fokus: mögliche Abwanderungssignale + High-Value-Profile für F2P. Pilotkunde: PlayNova Games.", d11t: "Schritt 2 · Kunde & Daten", d11p: "APIs evaluiert (Steam ✓, OpenDota ✗ Timeouts). Reales Schema in der DB.", d12t: "Schritt 3 · Echter Datensatz", d12p: ": 18.099 Reviews → 16.447 gelabelt.", d13t: "Schritt 4 · Analyse", d13p: ": frühes Engagement, Phase pro Titel, Vote≠Retention.", d14t: "Schritt 5 · Lösung", d14p: " leak-frei + ", d14p2: ": ROC 0,89–0,92 pro Spiel.", faqT: "Fragen, die euer CTO stellen würde", q1: "Woher kommen die Daten?", a1: "Aus Steams öffentlicher Review-API (ohne Key): 18.099 Reviews aus 6 F2P-Spielen vom 2026-09-14. Erneut ladbarer Rohdatensatz, versionierte DB und Summary, Herkunft in <code>docs/08_datos_reales.md</code>.", q2: "Bedeuten 91 % bei Fall Guys, dass 91 % seiner Spieler gingen?", a2: "Nein: Es ist der Anteil in unserer Reviewer-Stichprobe in der definierten Kategorie. Reviewer repräsentieren nicht alle Spieler. Was generalisiert, sind die Zusammenhänge, Titel für Titel validiert.", q3: "Leakage? Signalalter wiegt 0,50…", a3: "Echtes Signal (Review-Tempo = Titel-Momentum), aber mit ungleichen Fenstern: als Limitation dokumentiert. Das Modell sieht nie Recency oder Gesamtstunden; der Pilot nutzt fixe Fenster und eure echten Events.", q4: "Haben wir echte Ausgaben pro Spieler?", a4: "Nein. Wir nutzen einen Näherungsindikator (Top-25 % Stunden + empfiehlt), überall so ausgewiesen. Im Echtprojekt ersetzt durch PlayNova-Games-Kaufdaten.", q5: "Ist die Demo exakt das Produktivmodell?", a5: "Nein: illustrative Demo, kalibriert, um Signale in Entscheidungen zu übersetzen. Das echte Modell liegt in <code>models/real_*.pkl</code>; im Pilot exposen wir <code>/score</code> auf euren Daten.", q6: "Warum variiert F1 pro Titel, wenn ROC überall gut ist?", a6: "Weil die Prävalenz von 5 % (Dota 2, Apex) bis 91 % (Fall Guys) reicht und wir einen globalen Threshold (0,65) aus der aggregierten Validierung nutzen. ROC misst das Ranking je Spiel (0,891–0,924 in allen 6); F1 hängt vom Cut ab. Im Pilot kalibrieren wir den Threshold pro Titel." },
  foot: { title: "PlayNova, finden wir gemeinsam heraus, wie viele Spieler wir zurückgewinnen können?", sub: "ChurnGuard verspricht nicht, die Zukunft zu kennen. Es hilft, Signale früher zu sehen und zu entscheiden, wo zu handeln ist. 4 Wochen · 2.500 € · echte Daten · kontrolliertes Experiment.", cta: "Pilot anfragen · 2.500 € →", base: "ChurnGuard — NO PAIN NO GAME · 2026<br>Öffentliche Steam-Daten (18.099 Reviews, 2026-09-14) · Pilotkunde: PlayNova Games", top: "nach oben ↑" },
  sim: { levelHigh: "🔴 Hohes Risiko", levelMid: "🟡 Mittleres Risiko", levelLow: "🟢 Niedriges Risiko", motiveEarly: "Geringes frühes Engagement (Q1: 35,7 % Churn)", actionEarly: "Personalisiertes Onboarding + Daily-Event in 24 h.", motiveOld: "Altes Signal bei kaltem Titel", actionOld: "Win-back-Kampagne + Return-Bundle.", motiveNoRec: "Empfiehlt nicht (29,6 % Churn)", actionNoRec: "Proaktiver Support + Save-Angebot.", motiveDecline: "Titel in Schrumpfphase", actionDecline: "Return-Content/Event + Reminder.", motiveHealthy: "Gesundes Profil", actionHealthy: "Kadenz halten; Season-Pass als Booster.", motiveLabel: "Wahrscheinlicher Grund:", actionLabel: "Playbook-Aktion:", budgetA: "in der angenäherten High-Value-Gruppe (19,9 % unserer Stichprobe)", budgetB: "potenzieller Wert bei LTV $", budgetC: "Schätzung auf Proxy-Basis, keine Umsatzgarantie. Im Echtprojekt ersetzt durch echte PlayNova-Games-Daten.", lbSuffix: "(Esc oder Klick daneben zum Schließen)" }
}
};

function __t(path) {
  var lang = window.__lang || "es";
  var d = I18N[lang] || I18N.es;
  var parts = path.split(".");
  var v = d;
  for (var i = 0; i < parts.length; i++) { v = v && v[parts[i]]; }
  if (typeof v === "string") return v;
  var e = I18N.es;
  for (var j = 0; j < parts.length; j++) { e = e && e[parts[j]]; }
  return typeof e === "string" ? e : "";
}

function setLang(l) {
  if (!I18N[l]) l = "es";
  window.__lang = l;
  try { localStorage.setItem("churnguard-lang", l); } catch (e) {}
  document.documentElement.lang = l;
  var d = I18N[l];
  var nodes = document.querySelectorAll("[data-i18n]");
  for (var i = 0; i < nodes.length; i++) {
    var k = nodes[i].getAttribute("data-i18n");
    var v = k.split(".").reduce(function (o, p) { return o && o[p]; }, d);
    if (typeof v === "string") nodes[i].textContent = v;
  }
  var htmlNodes = document.querySelectorAll("[data-i18n-html]");
  for (var j = 0; j < htmlNodes.length; j++) {
    var k2 = htmlNodes[j].getAttribute("data-i18n-html");
    var v2 = k2.split(".").reduce(function (o, p) { return o && o[p]; }, d);
    if (typeof v2 === "string") htmlNodes[j].innerHTML = v2;
  }
  if (d._meta) {
    document.title = d._meta.title;
    var m = document.querySelector('meta[name="description"]');
    if (m) m.setAttribute("content", d._meta.description);
  }
  var sel = document.getElementById("langSelect");
  if (sel) sel.value = l;
  if (typeof updateSim === "function") { try { updateSim(); } catch (e) {} }
  if (typeof renderBudget === "function") { try { renderBudget(); } catch (e) {} }
}

document.addEventListener("DOMContentLoaded", function () {
  var saved = "es";
  try { saved = localStorage.getItem("churnguard-lang") || "es"; } catch (e) {}
  if (!I18N[saved]) {
    var nav = (navigator.language || "es").slice(0, 2).toLowerCase();
    saved = I18N[nav] ? nav : "es";
  }
  setLang(saved);
});
